"use client";
import {useEffect,useMemo,useState} from "react";

type Case={id:string,name:string,owner:string,actual:number,plan:number,lbe:number,volume:number,rate:number,mix:number,timing:number,labor:number,throughput:number,utilization:number,confidence:number};
const cases:Case[]=[
{id:"CC-410",name:"Aseptic Operations",owner:"Manufacturing",actual:4820000,plan:4300000,lbe:4580000,volume:160000,rate:210000,mix:90000,timing:60000,labor:112,throughput:88,utilization:73,confidence:82},
{id:"CC-225",name:"Quality Control",owner:"Quality",actual:1960000,plan:2180000,lbe:2050000,volume:-80000,rate:-45000,mix:-25000,timing:-70000,labor:96,throughput:104,utilization:87,confidence:77},
{id:"CC-730",name:"Facilities & Utilities",owner:"Engineering",actual:2870000,plan:2440000,lbe:2630000,volume:45000,rate:260000,mix:35000,timing:90000,labor:101,throughput:100,utilization:91,confidence:74},
{id:"CC-520",name:"Packaging",owner:"Operations",actual:3410000,plan:3280000,lbe:3360000,volume:220000,rate:-60000,mix:-20000,timing:-10000,labor:106,throughput:117,utilization:84,confidence:86},
{id:"CC-180",name:"Site Administration",owner:"Site Leadership",actual:1210000,plan:1080000,lbe:1160000,volume:0,rate:55000,mix:15000,timing:60000,labor:104,throughput:100,utilization:89,confidence:70},
];
const agents=[
["DS","Data Steward","Validates source completeness and mappings","#70d7ff"],
["VA","Variance Analyst","Decomposes volume, rate, mix, and timing","#88efc0"],
["OL","Operations Liaison","Connects financial movement to operating signals","#f6c85f"],
["FC","Forecast Challenger","Contests the outlook and tests alternate baselines","#ff7c72"],
["RA","Risk Auditor","Checks control, cutoff, and anomaly exposure","#d79cff"],
["FS","Finance Synthesizer","Builds an accountable management brief","#eef5f2"],
];
const stages=["VALIDATE","DECOMPOSE","CONNECT","CHALLENGE","SIMULATE","BRIEF"];
const fmt=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0,notation:Math.abs(n)>999999?"compact":"standard"}).format(n);
function analyze(c:Case){
 const variance=c.actual-c.plan,vsLbe=c.actual-c.lbe,pct=variance/Math.max(Math.abs(c.plan),1)*100;
 const drivers=[["Volume",c.volume],["Rate",c.rate],["Mix",c.mix],["Timing",c.timing]].sort((a,b)=>Math.abs(Number(b[1]))-Math.abs(Number(a[1])));
 const dominant=String(drivers[0][0]),unexplained=variance-[c.volume,c.rate,c.mix,c.timing].reduce((a,b)=>a+b,0);
 const opRisk=Math.min(100,Math.round(Math.abs(pct)*2.5+Math.max(0,100-c.utilization)*.35+Math.abs(100-c.throughput)*.5));
 const material=Math.abs(pct)>8?"Material":Math.abs(pct)>4?"Watch":"Within range";
 return{variance,vsLbe,pct,drivers,dominant,unexplained,opRisk,material,reasons:[`${fmt(variance)} (${pct.toFixed(1)}%) versus plan`,`${dominant} is the largest modeled driver`,`Throughput index ${c.throughput}; utilization ${c.utilization}%`],counter:`The ${dominant.toLowerCase()} attribution may be absorbing a cutoff or mapping issue. ${fmt(Math.abs(unexplained))} remains outside the four-driver bridge.`,action:pct>8?"Contain cost and reforecast":pct<-8?"Validate underspend and protect capacity":"Monitor in next close",owner:c.owner};
}
export default function Home(){
 const [selected,setSelected]=useState(cases[0]),[draft,setDraft]=useState(cases[0]),[view,setView]=useState<"case"|"portfolio"|"method">("case");
 const [running,setRunning]=useState(false),[stage,setStage]=useState(-1),[elapsed,setElapsed]=useState(0),[done,setDone]=useState(false),[trace,setTrace]=useState(false),[disposition,setDisposition]=useState("Pending");
 const [scenario,setScenario]=useState({volume:draft.volume,rate:draft.rate,labor:draft.labor,throughput:draft.throughput});
 const result=useMemo(()=>analyze(draft),[draft]); const simulated=useMemo(()=>analyze({...draft,...scenario}),[draft,scenario]);
 useEffect(()=>{if(!running)return;const start=Date.now();const t=setInterval(()=>{const e=(Date.now()-start)/1000;setElapsed(e);setStage(Math.min(5,Math.floor(e/3)));if(e>=18){clearInterval(t);setRunning(false);setDone(true);setStage(5)}},100);return()=>clearInterval(t)},[running]);
 const load=(c:Case)=>{setSelected(c);setDraft({...c});setScenario({volume:c.volume,rate:c.rate,labor:c.labor,throughput:c.throughput});setDone(false);setStage(-1);setDisposition("Pending");setView("case")};
 const run=()=>{setElapsed(0);setStage(0);setDone(false);setRunning(true);setDisposition("Pending")}; const skip=()=>{setRunning(false);setStage(5);setElapsed(18);setDone(true)};
 const update=(k:keyof Case,n:number)=>{setDraft(x=>({...x,[k]:n}));setDone(false)};
 const exportBrief=()=>{const blob=new Blob([JSON.stringify({system:"Financial Variance Command Center",generated:new Date().toISOString(),notice:"Synthetic prototype; no SAP connection.",case:draft,analysis:result,disposition},null,2)],{type:"application/json"});const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`${draft.id}-management-brief.json`;a.click();URL.revokeObjectURL(u)};
 return <main>
 <header><div className="brand"><i>FV</i><div>Financial Variance Command Center<small>Decision Systems Lab · System 007</small></div></div><nav>{(["case","portfolio","method"] as const).map(v=><button className={view===v?"on":""} onClick={()=>setView(v)} key={v}>{v}</button>)}</nav><span className="demo">● Synthetic prototype</span></header>
 {view==="portfolio"?<Portfolio load={load}/>:view==="method"?<Method/>:<>
 <section className="hero"><div><p className="eyebrow">Financial investigation · {draft.id}</p><h1>Every variance<br/><em>deserves a theory.</em></h1><p>The standardized financial model becomes an investigation surface: six bounded agents validate the record, explain the bridge, challenge the forecast, and prepare a decision for human review.</p></div><aside><span>CURRENT CASE</span><strong>{draft.name}</strong><p>{draft.owner} · Actual {fmt(draft.actual)}</p><button onClick={()=>setView("portfolio")}>Open variance portfolio ↗</button></aside></section>
 <div className="notice"><b>RESEARCH PROTOTYPE</b> Synthetic data · no live SAP, Power BI, or autonomous journal entries · current release uses deterministic browser calculations</div>
 <section className="work">
  <aside className="panel inputs"><Title n="01" t="Financial record"/><label>Variance case<select value={selected.id} onChange={e=>load(cases.find(c=>c.id===e.target.value)!) }>{cases.map(c=><option value={c.id} key={c.id}>{c.id} · {c.name}</option>)}</select></label><div className="grid">
  {(["actual","plan","lbe","volume","rate","mix","timing","labor","throughput","utilization"] as (keyof Case)[]).map(k=><Num key={k} label={k} value={Number(draft[k])} set={n=>update(k,n)}/>)}</div>
  <button className="run" onClick={run} disabled={running}>{running?"Agents investigating…":"Run variance review"}<b>⌁</b></button></aside>
  <section className="panel room"><Title n="02" t="Investigation room" extra={running?elapsed.toFixed(1)+"s":"READY"}/><div className="progress"><i style={{width:`${done?100:running?elapsed/18*100:0}%`}}/><span>{stage<0?"AWAITING REVIEW":stages[stage]}</span><b>{Math.round(done?100:running?elapsed/18*100:0)}%</b></div>
  <div className="scene"><div className="board"><span>SHARED VARIANCE BRIDGE</span><h3>{stage<0?"No active investigation":stage<2?`${fmt(result.variance)} vs Plan`:result.dominant+" DRIVER"}</h3>{stage>=1&&result.drivers.map(([k,v])=><div className="bar" key={String(k)}><b>{k}</b><i style={{width:`${Math.min(100,Math.abs(Number(v))/Math.max(...result.drivers.map(x=>Math.abs(Number(x[1]))))*100)}%`}}/><span>{fmt(Number(v))}</span></div>)}</div>
  {agents.map((a,i)=><div className={`agent ag${i} ${stage>=0&&(i===5||stage>=Math.min(i,4))?"active":""}`} key={a[1]} style={{"--c":a[3]} as React.CSSProperties}><div className="bubble">{stage<0?"Standing by":stage<2?a[2]:stage===3&&i===3?result.counter:stage>=4?"Evidence recorded":a[2]}</div><div className="face">{a[0]}</div><b>{a[1]}</b></div>)}
  <div className="consensus"><span>EXPLANATION COVERAGE</span><i><b style={{width:`${stage<2?20:Math.min(96,draft.confidence)}%`}}/></i><strong>{stage<3?"Forming":stage===3?"Contested":draft.confidence+"%"}</strong></div></div>
  <div className="steps">{stages.map((s,i)=><span className={i<=stage?"lit":""} key={s}><i/>{s}</span>)}</div>{running&&<button className="skip" onClick={skip}>Skip to brief →</button>}</section>
 </section>
 <section className="outcome"><Head n="03" title={<>The agents explain.<br/><em>Management decides.</em></>}/>{!done?<div className="locked">Run the variance review to unlock the management brief.</div>:<>
 <div className="brief"><div><span>ASSESSMENT</span><h2>{result.material}</h2><p>{result.action} · Owner: {result.owner}</p></div><div className="score"><span>ACTUAL VS PLAN</span><strong>{fmt(result.variance)}</strong><p>{result.pct.toFixed(1)}%</p></div><div className="stats"><Metric k="Actual" v={fmt(draft.actual)}/><Metric k="Plan" v={fmt(draft.plan)}/><Metric k="LBE delta" v={fmt(result.vsLbe)}/><Metric k="Risk" v={result.opRisk+"/100"}/></div></div>
 <div className="evidence"><article><span>LEADING EXPLANATION</span>{result.reasons.map(x=><p key={x}>↳ {x}</p>)}</article><article className="challenge"><span>FORECAST CHALLENGE</span><p>{result.counter}</p></article><article><span>DECISION REQUEST</span><p>{result.action}</p><small>Human disposition required; no transaction is created.</small></article></div>
 <div className="buttons"><div>{["Accept explanation","Request evidence","Escalate forecast"].map(x=><button className={disposition===x?"chosen":""} onClick={()=>setDisposition(x)} key={x}>{x}</button>)}</div><div><button onClick={()=>setTrace(true)}>Open full trace ↗</button><button onClick={exportBrief}>Export brief ↓</button></div></div><p className="logged">Disposition: <b>{disposition}</b> · retained in this local session only.</p></>}</section>
 <section className="lab"><Head n="04" title={<>What would have to change<br/><em>to change the outlook?</em></>}/><div className="sim"><div>{Object.entries(scenario).map(([k,v])=><label key={k}><span>{k}<b>{k==="volume"||k==="rate"?fmt(v):v}</b></span><input type="range" value={v} min={k==="volume"||k==="rate"?-400000:60} max={k==="volume"||k==="rate"?500000:140} step={k==="volume"||k==="rate"?10000:1} onChange={e=>setScenario(x=>({...x,[k]:Number(e.target.value)}))}/></label>)}</div><aside><span>BASELINE → SCENARIO</span><h3>{result.material} → <em>{simulated.material}</em></h3><Metric k="Variance" v={`${fmt(result.variance)} → ${fmt(simulated.variance)}`}/><Metric k="Largest driver" v={`${result.dominant} → ${simulated.dominant}`}/><Metric k="Risk" v={`${result.opRisk} → ${simulated.opRisk}`}/></aside></div></section>
 </>}
 <footer><span>FINANCIAL VARIANCE COMMAND CENTER · FVCC-0.6</span><p>Explainable financial investigation for accountable management review.</p><a href="https://decisionsystemslab.org/systems/site-financial-health-engine">Research notebook ↗</a></footer>
 {trace&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setTrace(false)}><div className="drawer"><div className="drawhead"><div><span>COMPLETE TRACE</span><h2>{draft.id} · {result.material}</h2></div><button onClick={()=>setTrace(false)}>Close ×</button></div>{stages.map((s,i)=><article key={s}><b>0{i+1}</b><div><h3>{s}</h3><p>{i===0?"Source schema, GL mapping, and scenario completeness validated.":i===1?result.drivers.map(x=>`${x[0]} ${fmt(Number(x[1]))}`).join(" · "):i===2?`Labor ${draft.labor}, throughput ${draft.throughput}, utilization ${draft.utilization}%`:i===3?result.counter:i===4?`Scenario sensitivity evaluated against plan and LBE.`:`${result.material}: ${result.action}`}</p></div></article>)}</div></div>}
 </main>
}
function Num({label,value,set}:{label:string,value:number,set:(n:number)=>void}){return <label>{label}<input type="number" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function Title({n,t,extra}:{n:string,t:string,extra?:string}){return <div className="title"><div><span>{n}</span><h2>{t}</h2></div>{extra&&<b>{extra}</b>}</div>}
function Head({n,title}:{n:string,title:React.ReactNode}){return <div className="head"><p>{n} · HUMAN-CENTERED FINANCE</p><h2>{title}</h2></div>}
function Metric({k,v}:{k:string,v:string}){return <div className="metric"><span>{k}</span><strong>{v}</strong></div>}
function Portfolio({load}:{load:(c:Case)=>void}){const rows=cases.map(c=>({c,r:analyze(c)})).sort((a,b)=>Math.abs(b.r.pct)-Math.abs(a.r.pct));return <section className="portfolio"><div className="porthero"><p className="eyebrow">Site financial portfolio</p><h1>Attention follows<br/><em>materiality.</em></h1><p>Five synthetic cost-center cases ranked by absolute plan variance and operational risk.</p></div><div className="kpis"><Metric k="Net variance" v={fmt(rows.reduce((s,x)=>s+x.r.variance,0))}/><Metric k="Material cases" v={String(rows.filter(x=>x.r.material==="Material").length)}/><Metric k="Cost centers" v={String(rows.length)}/><Metric k="Unexplained" v={fmt(rows.reduce((s,x)=>s+Math.abs(x.r.unexplained),0))}/></div><div className="panel queue"><Title n="QUEUE" t="Ranked variance investigations"/><div className="tr th"><span>Cost center</span><span>Owner</span><span>Actual</span><span>Plan variance</span><span>Driver</span><span/></div>{rows.map(({c,r})=><button className="tr" onClick={()=>load(c)} key={c.id}><span><b>{c.id}</b><small>{c.name}</small></span><span>{c.owner}</span><span>{fmt(c.actual)}</span><span className={r.variance>0?"bad":"good"}>{fmt(r.variance)}<small>{r.pct.toFixed(1)}%</small></span><span>{r.dominant}</span><span>Investigate →</span></button>)}</div></section>}
function Method(){return <section className="method"><div className="porthero"><p className="eyebrow">Method · FVCC-0.6</p><h1>A narrative must<br/><em>survive a challenge.</em></h1><p>The current release is a deterministic interaction prototype: no external LLM calls, no SAP connection, and no claim of empirical improvement.</p></div><div className="methodgrid"><article><span>01 · BACKBONE</span><h2>Unified semantic model</h2><p>Actual, Plan, and LBE share cost center, GL, category, scenario, period, and amount dimensions.</p></article><article><span>02 · BRIDGE</span><h2>Driver decomposition</h2><p>Volume, rate, mix, and timing convert a number into an inspectable causal hypothesis.</p></article><article><span>03 · DISSENT</span><h2>Mandatory challenge</h2><p>The forecast explanation is contested before synthesis. Unexplained residuals remain visible.</p></article><article><span>04 · AUTHORITY</span><h2>Human disposition</h2><p>The system prepares a brief. Finance and operations retain ownership of the decision and controls.</p></article></div></section>}
